server:
  port: 19904                                                # 配置端口号
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: frame4j-mq
  zipkin:
    base-url: http://127.0.0.1:9411/
    ###全部采集
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 112.74.165.209
    port: 8883
    username: guest
    password: guest
###服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/