server:
  port: 19904                                                # 配置端口号
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: frame4j-mq
  zipkin:
    base-url: http://127.0.0.1:9411/
    ###全部采集
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    host: 112.74.165.209
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/microiot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8    #第一个坑 mysql时区问题  serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false  #懒加载序列化出错  Could not write content: No serializer found for class and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) )
    time-zone: GMT+8  #时间日区
    date-format: yyyy-MM-dd HH:mm:ss  #jackson日期格式
  mqtt:             #MQTT配置信息
    username: guest     #MQTT-用户名
    password: guest     #MQTT-密码
    url: tcp://112.74.165.209:1885      #MQTT-服务器连接地址，如果有多个，用逗号隔开，
    client:
      id: mqttId     #MQTT-连接服务器默认客户端ID
    default:
      topic: /cc3200/TMP006    #MQTT-默认的消息推送主题，实际可在调用接口时指定
    completionTimeout: 3000   #连接超时

###服务注册地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:20000/eureka/

mybatis:
  configuration:
    map-underscore-to-camel-case: true